# Generated by Django 4.2.4 on 2023-12-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('open_date', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('images', models.ImageField(upload_to='media/branch_img')),
            ],
        ),
    ]
