# Generated by Django 4.2.4 on 2023-12-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='images',
            field=models.ImageField(blank=True, upload_to='media/branch_img'),
        ),
    ]
