# Generated by Django 4.2.4 on 2023-12-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='images',
        ),
    ]
